services:
  nginx:
    restart: always
    image: nginx:1.25.3-alpine
    ports:
      - 80:80
      - 433:433
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
  php:
    build:
      dockerfile: docker/php/Dockerfile
    environment:
      - MARIADB_DATABASE
      - MARIADB_USER
      - MARIADB_PASSWORD
    volumes:
      - .:/var/www/html
  mysql:
    build:
      dockerfile: docker/mysql/Dockerfile
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD
      - MARIADB_DATABASE
      - MARIADB_USER
      - MARIADB_PASSWORD
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
    driver: local
